name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:  
  test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache npm and Next.js build cache
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: main-build-cache-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            main-build-cache-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: npm run test
      
      - name: Install Playwright Browsers
        run: npm install @playwright/test
      
      - name: Run playwright
        run: npm run test:playwright
      
      - name: Run formatter
        run: npm run format

      - name: Run linter
        run: npm run lint      
