name: Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Cache npm and Next.js build cache
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: main-build-cache-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            main-build-cache-${{ hashFiles('**/package-lock.json') }}-
      
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "installing dependencies for build"
          npm install

      - name: Build project
        run: npm run build
  
  # After build is successful, run tests on code
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache npm and Next.js build cache
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: main-build-cache-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            main-build-cache-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "installing dependencies for test"
          npm install

      - name: Run tests
        run: npm run test

      - name: Run linter
        run: npm run lint