name: Vercel Deployment

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache npm and Next.js build cache
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: main-build-cache-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            main-build-cache-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "installing dependencies for build"
          npm install

      - name: Build project
        run: npm run build

  # After build is successful, deploy to Vercel
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache global npm packages
        uses: actions/cache@v4
        id: cache-vercel-cli
        with:
          path: ~/.npm-global
          key: vercel-cli-cache-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            vercel-cli-cache-${{ hashFiles('**/package-lock.json') }}-

      - name: Install Vercel CLI (only if cache miss)
        if: steps.cache-vercel-cli.outputs.cache-hit != 'true'  # Run only if cache miss
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          echo "deploying to Vercel..."
          vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --confirm
          echo "deployment complete"