name: Vercel Deployment

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Vercel CLI
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-vercel
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          echo "deploying to Vercel..."
          vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --confirm
          echo "deployment complete"